@extends('layouts.admin')

@section('title', 'Berita Acara Maker')
@section('page-title', 'Berita Acara Maker')

@section('content')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
    .ba-card { transition: transform .15s ease, box-shadow .15s ease; }
    .ba-card:hover { transform: translateY(-2px); box-shadow: 0 .5rem 1rem rgba(30,58,95,.12)!important; }
    .ba-paper { width:100%; max-width:210mm; min-height:297mm; box-sizing:border-box; margin:auto; background:#fff; padding:18mm 18mm 22mm; font-family:Arial,sans-serif; color:#282828; font-size:10pt; line-height:1.4; overflow-wrap:anywhere; }
    .ba-paper .ba-header { display:flex; justify-content:space-between; align-items:flex-end; border-bottom:2pt solid #00529B; padding-bottom:8pt; }
    .ba-paper .ba-logo { height:42pt; max-width:150pt; object-fit:contain; }
    .ba-paper .ba-company { margin-top:5pt; font-size:10pt; font-weight:700; letter-spacing:.5pt; text-transform:uppercase; }
    .ba-paper .ba-contact { max-width:230pt; text-align:right; font-size:8pt; line-height:1.2; color:#4A5568; }
    .ba-paper .ba-title { margin:17pt 0 4pt; text-align:center; font-size:16pt; font-weight:700; letter-spacing:1.5pt; }
    .ba-paper .ba-number { margin:0 0 14pt; text-align:center; font-size:9pt; color:#4A5568; }
    .ba-paper table { width:100%; border-collapse:collapse; }
    .ba-paper .ba-detail { margin-bottom:14pt; break-inside:avoid; page-break-inside:avoid; }
    .ba-paper .ba-detail td { border:1pt solid #CBD5E1; padding:5pt 7pt; vertical-align:top; }
    .ba-paper .ba-detail td:nth-child(odd) { width:19%; font-weight:700; background:#F1F5F9; }
    .ba-paper .ba-section-title { margin:13pt 0 6pt; padding-bottom:3pt; border-bottom:1pt solid #00529B; color:#00529B; font-size:11pt; font-weight:700; text-transform:uppercase; break-after:avoid; page-break-after:avoid; }
    .ba-paper .ba-personnel th, .ba-paper .ba-personnel td, .ba-paper .ba-timeline th, .ba-paper .ba-timeline td { border:1pt solid #CBD5E1; padding:5pt 7pt; vertical-align:top; }
    .ba-paper .ba-personnel th, .ba-paper .ba-timeline th { background:#00529B; color:#fff; font-weight:700; text-align:left; }
    .ba-paper .ba-timeline td:first-child { width:20%; white-space:nowrap; font-weight:700; }
    .ba-paper .ba-result { padding:8pt 10pt; border:1pt solid #00529B; background:#F8FAFC; break-inside:avoid; page-break-inside:avoid; }
    .ba-paper .ba-documentation { display:grid; grid-template-columns:repeat(2,1fr); gap:10pt; break-inside:avoid; page-break-inside:avoid; }
    .ba-paper .ba-documentation figure { margin:0; break-inside:avoid; page-break-inside:avoid; }
    .ba-paper .ba-documentation img { display:block; width:100%; height:95pt; object-fit:cover; border:1pt solid #CBD5E1; }
    .ba-paper .ba-documentation figcaption { margin-top:3pt; font-size:8pt; color:#4A5568; text-align:center; }
    .ba-paper .ba-signatures { margin-top:28pt; display:grid; grid-template-columns:repeat(3,1fr); gap:12pt; text-align:center; break-inside:avoid; page-break-inside:avoid; }
    .ba-paper .ba-signature { min-height:80pt; display:flex; flex-direction:column; justify-content:space-between; }
    .ba-paper .ba-signature strong { font-size:9pt; }
    #ba-modal .modal-dialog, #ba-settings-modal .modal-dialog { height:calc(100% - 1rem); max-height:calc(100% - 1rem); }
    #ba-modal .modal-content, #ba-settings-modal .modal-content { height:100%; max-height:100%; }
    #ba-modal form, #ba-settings-modal form { display:flex; flex:1 1 auto; min-height:0; flex-direction:column; }
    #ba-modal .modal-body, #ba-settings-modal .modal-body { overflow-y:auto; min-height:0; }
    #ba-modal .modal-footer, #ba-settings-modal .modal-footer { flex-shrink:0; }
    .ba-paper.ba-export { width:174mm; max-width:174mm; padding:0; min-height:0; margin:0; }
    @media print { @page { size:A4 portrait; margin:18mm; } html,body { margin:0!important; padding:0!important; width:100%!important; overflow:visible!important; } body * { visibility:hidden!important; } #ba-preview-modal,#ba-preview-modal .modal-dialog,#ba-preview-modal .modal-content,#ba-preview-modal .modal-body { display:block!important; position:static!important; width:100%!important; max-width:none!important; height:auto!important; min-height:0!important; margin:0!important; padding:0!important; border:0!important; overflow:visible!important; box-shadow:none!important; } #ba-paper,#ba-paper * { visibility:visible!important; } #ba-paper { position:static; width:100%!important; max-width:none!important; min-height:0; padding:0; margin:0; box-shadow:none!important; overflow:visible!important; } .no-print { display:none!important; } }
</style>

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h4 class="mb-1 font-headline"><i class="fas fa-file-circle-check text-success me-2"></i>Berita Acara Maker</h4><p class="text-muted mb-0">Dokumentasikan kegiatan operasional IT dalam format berita acara resmi.</p></div>
    <div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="ba-settings-btn"><i class="fas fa-gear me-1"></i>Pengaturan</button><button class="btn btn-success" id="new-ba-btn"><i class="fas fa-plus me-1"></i>Berita Acara Baru</button></div>
</div>
<div class="card shadow-sm border-0 mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-md-7"><div class="input-group"><span class="input-group-text bg-white"><i class="fas fa-search"></i></span><input id="ba-search" class="form-control" placeholder="Cari nomor, judul, atau lokasi..."></div></div><div class="col-md-3"><select id="ba-status-filter" class="form-select"><option value="">Semua status</option><option value="Draft">Draft</option><option value="Selesai">Selesai</option></select></div><div class="col-md-2 text-md-end"><span class="text-muted small" id="ba-count">Total: 0 BA</span><button class="btn btn-sm btn-link text-danger ms-2" id="ba-reset-data">Reset sample</button></div></div></div></div>
<div id="ba-grid" class="row g-4"></div>

<div class="modal fade" id="ba-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-success text-white"><h5 class="modal-title" id="ba-modal-title"><i class="fas fa-file-circle-check me-2"></i>Buat Berita Acara Baru</h5><div class="d-flex align-items-center gap-2"><button type="button" class="btn btn-sm btn-light text-success" id="ba-toggle-ai"><i class="fas fa-wand-magic-sparkles me-1"></i>AI Auto-Fill</button><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Tutup"></button></div></div><form id="ba-form"><div class="modal-body">
    <div id="ba-ai-panel" class="alert alert-success d-none"><div class="d-flex justify-content-between align-items-center mb-2"><strong><i class="fas fa-robot me-1"></i>AI Berita Acara Generator</strong><small>Masukkan skenario kegiatan</small></div><div class="input-group input-group-sm"><textarea id="ba-ai-topic" class="form-control" rows="2" placeholder="Contoh: Pada 24 Agustus 2026 tim IT melakukan relokasi server di ruang data center..." ></textarea><button type="button" class="btn btn-success" id="ba-generate-ai"><i class="fas fa-sparkles me-1"></i>Generate</button></div><div id="ba-ai-status" class="small mt-2"></div></div>
    <input type="hidden" id="ba-id"><div class="row g-3"><div class="col-md-4"><label class="form-label">Nomor BA</label><input id="ba-number" class="form-control" required placeholder="BA/IT-TDI/VIII/2026"></div><div class="col-md-5"><label class="form-label">Judul Kegiatan</label><input id="ba-title" class="form-control" required placeholder="Relokasi perangkat server"></div><div class="col-md-3"><label class="form-label">Status</label><select id="ba-status" class="form-select"><option>Draft</option><option>Selesai</option></select></div><div class="col-md-4"><label class="form-label">Tanggal Pelaksanaan</label><input id="ba-date" type="date" class="form-control" required></div><div class="col-md-4"><label class="form-label">Waktu Mulai</label><input id="ba-start" type="time" class="form-control"></div><div class="col-md-4"><label class="form-label">Waktu Selesai</label><input id="ba-end" type="time" class="form-control"></div><div class="col-md-8"><label class="form-label">Lokasi</label><input id="ba-location" class="form-control" required placeholder="Data Center / Kantor Pusat"></div><div class="col-md-4"><label class="form-label">Durasi Operasional</label><input id="ba-duration" class="form-control" placeholder="3 jam 30 menit"></div></div>
    <hr><div class="d-flex justify-content-between align-items-center mb-2"><div><h6 class="mb-0">Personel Pelaksana</h6><small class="text-muted">Tambahkan seluruh personel TDI dan vendor.</small></div><button type="button" class="btn btn-sm btn-outline-success" id="ba-add-person"><i class="fas fa-plus me-1"></i>Tambah Personel</button></div><div id="ba-personnel-container"></div>
    <hr><div class="d-flex justify-content-between align-items-center mb-2"><div><h6 class="mb-0">Kronologi Kegiatan</h6><small class="text-muted">Susun timeline pekerjaan secara berurutan.</small></div><button type="button" class="btn btn-sm btn-outline-success" id="ba-add-timeline"><i class="fas fa-plus me-1"></i>Tambah Kronologi</button></div><div id="ba-timeline-container"></div>
    <div class="row g-3 mt-1"><div class="col-md-8"><label class="form-label">Hasil / Status Akhir</label><textarea id="ba-result" class="form-control" rows="3" required placeholder="Pekerjaan selesai dan perangkat telah berfungsi normal."></textarea></div><div class="col-md-4"><label class="form-label">Catatan Tambahan</label><textarea id="ba-notes" class="form-control" rows="3" placeholder="Catatan, tindak lanjut, atau rekomendasi"></textarea></div><div class="col-12"><label class="form-label">Dokumentasi Kegiatan</label><input id="ba-documentation-files" type="file" accept="image/*" multiple class="form-control"><small class="text-muted">Upload satu atau beberapa gambar dokumentasi kegiatan.</small><div id="ba-documentation-preview" class="row g-2 mt-1"></div></div><div class="col-md-4"><label class="form-label">Pelaksana IT TDI</label><input id="ba-tdi-signer" class="form-control" placeholder="Nama pelaksana"></div><div class="col-md-4"><label class="form-label">Pelaksana Vendor</label><input id="ba-vendor-signer" class="form-control" placeholder="Nama vendor / kosongkan jika tidak ada"></div><div class="col-md-4"><label class="form-label">Supervisor IT</label><input id="ba-supervisor" class="form-control" value="Iqbal Taufik Akbar"></div></div>
    </div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-success"><i class="fas fa-save me-1"></i>Simpan Berita Acara</button></div></form></div></div></div>

<div class="modal fade" id="ba-settings-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-building text-success me-2"></i>Pengaturan Kop Surat & AI</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><form id="ba-settings-form"><div class="modal-body"><label class="form-label">Nama Perusahaan</label><input id="ba-company-name" class="form-control mb-3" required><label class="form-label">Alamat Kantor</label><textarea id="ba-company-address" rows="2" class="form-control mb-3" required></textarea><label class="form-label">Email IT Support</label><input id="ba-company-email" type="email" class="form-control mb-3" required><label class="form-label">Default Unit Kerja</label><input id="ba-default-dept" class="form-control mb-3" required><div class="p-3 rounded border border-success-subtle bg-success-subtle mb-3"><label class="form-label fw-semibold">Provider AI</label><select id="ba-ai-provider" class="form-select form-select-sm mb-2"><option value="gemini">Gemini API</option><option value="openai">OpenAI-compatible</option></select><label class="form-label small">Base URL</label><input id="ba-ai-base-url" class="form-control form-control-sm mb-2"><label class="form-label small">API Key</label><input id="ba-api-key" type="password" class="form-control form-control-sm mb-2"><div class="input-group input-group-sm mb-2"><select id="ba-ai-model" class="form-select"><option value="">Load model terlebih dahulu</option></select><button type="button" class="btn btn-outline-success" id="ba-load-ai-models"><i class="fas fa-rotate me-1"></i>Load Models</button></div><div id="ba-ai-model-status" class="small text-muted">Model akan dimuat dari provider yang dipilih.</div></div><label class="form-label">Logo (opsional)</label><input id="ba-company-logo" type="file" accept="image/*" class="form-control form-control-sm"><div id="ba-logo-preview" class="mt-2"></div></div><div class="modal-footer"><button type="submit" class="btn btn-success">Simpan Pengaturan</button></div></form></div></div></div>

<div class="modal fade" id="ba-preview-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-dark text-white no-print"><h5 class="modal-title"><i class="fas fa-eye text-info me-2"></i>Pratinjau Berita Acara</h5><div><button id="ba-print" class="btn btn-sm btn-outline-light me-2"><i class="fas fa-print me-1"></i>Print</button><button id="ba-download-pdf" class="btn btn-sm btn-success me-2"><i class="fas fa-file-pdf me-1"></i>Download PDF</button><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div></div><div class="modal-body bg-secondary-subtle p-3 p-md-5"><div id="ba-paper" class="ba-paper shadow"></div></div></div></div></div>

<script>
document.addEventListener('DOMContentLoaded',()=>{
    const key='tdi_admin_berita_acara_v1', settingsKey='tdi_admin_memo_settings_v1';
    const defaults={companyName:'PT. TERA DATA INDONUSA Tbk.',address:'Jl. Inspeksi Pam No.168 17, RT.17/RW.4, Cakung, Jakarta 13910',email:'it.support@terra.co.id',defaultDept:'IT Department',logo:'',provider:'gemini',baseUrl:'https://generativelanguage.googleapis.com/v1beta',apiKey:'',model:''};
    const sample={id:'ba-1',number:'BA/IT-TDI/VIII/2026',title:'Pemeliharaan Infrastruktur Jaringan',status:'Selesai',date:'2026-08-24',start:'21:00',end:'23:30',location:'Data Center PT Tera Data Indonusa Tbk.',duration:'2 jam 30 menit',personnel:[{name:'Muhamad Habib Gusti',role:'IT TDI'},{name:'Master Fauza',role:'IT TDI'},{name:'IMV Technical Support',role:'Vendor'}],timeline:[{time:'21:00',detail:'Tim melakukan pemeriksaan kondisi perangkat dan konektivitas jaringan.'},{time:'22:00',detail:'Pemeliharaan dan penggantian konfigurasi perangkat dilakukan sesuai prosedur.'},{time:'23:30',detail:'Pengujian akhir selesai dan seluruh layanan kembali normal.'}],result:'Pekerjaan pemeliharaan selesai, layanan jaringan terverifikasi normal, dan tidak terdapat gangguan lanjutan.',notes:'Dokumentasi disimpan untuk kebutuhan operasional dan audit.',tdiSigner:'Muhamad Habib Gusti',vendorSigner:'IMV Technical Support',supervisor:'Iqbal Taufik Akbar',ai:true};
    const legacySettings=JSON.parse(localStorage.getItem(settingsKey)||'{}');
    let bas=JSON.parse(localStorage.getItem(key)||'null')||[sample], settings={...defaults,...legacySettings,...@json($adminSettings ?? [])};
    const $=id=>document.getElementById(id), modal=id=>window.bootstrap?.Modal.getOrCreateInstance($(id)), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const today=()=>new Date().toISOString().slice(0,10), formatDate=value=>value?new Date(value+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'}):'-';
    const persist=()=>localStorage.setItem(key,JSON.stringify(bas));
    function personnelHtml(item={}){return `<div class="row g-2 align-items-end mb-2 ba-personnel-row"><div class="col-md-6"><label class="form-label small">Nama Personel</label><input class="form-control form-control-sm person-name" required value="${esc(item.name)}"></div><div class="col-md-5"><label class="form-label small">Instansi / Peran</label><select class="form-select form-select-sm person-role"><option ${item.role==='IT TDI'?'selected':''}>IT TDI</option><option ${item.role==='Vendor'?'selected':''}>Vendor</option><option ${item.role==='User Department'?'selected':''}>User Department</option></select></div><div class="col-md-1"><button type="button" class="btn btn-sm btn-outline-danger remove-person" title="Hapus personel"><i class="fas fa-trash"></i></button></div></div>`;}
    function timelineHtml(item={}){return `<div class="row g-2 align-items-end mb-2 ba-timeline-row"><div class="col-md-3"><label class="form-label small">Waktu</label><input type="time" class="form-control form-control-sm timeline-time" required value="${esc(item.time)}"></div><div class="col-md-8"><label class="form-label small">Detail Kegiatan</label><textarea class="form-control form-control-sm timeline-detail" rows="1" required>${esc(item.detail)}</textarea></div><div class="col-md-1"><button type="button" class="btn btn-sm btn-outline-danger remove-timeline" title="Hapus kronologi"><i class="fas fa-trash"></i></button></div></div>`;}
    function render(){const q=($('ba-search').value||'').toLowerCase(), status=$('ba-status-filter').value, list=bas.filter(b=>(!status||b.status===status)&&[b.number,b.title,b.location].some(v=>(v||'').toLowerCase().includes(q)));$('ba-count').textContent=`Total: ${list.length} BA`;$('ba-grid').innerHTML=list.length?list.map(b=>`<div class="col-12 col-md-6 col-xl-4"><div class="card ba-card h-100 shadow-sm border-0"><div class="card-body"><div class="d-flex justify-content-between gap-2 mb-3"><span class="badge text-bg-success">${esc(b.number)}</span><span class="badge ${b.status==='Selesai'?'text-bg-success':'text-bg-warning'}">${esc(b.status)}</span></div><h5 class="card-title fs-6 fw-bold">${esc(b.title)}</h5><p class="small mb-1"><i class="fas fa-calendar me-1 text-muted"></i>${esc(formatDate(b.date))}</p><p class="small mb-2"><i class="fas fa-location-dot me-1 text-muted"></i>${esc(b.location)}</p><p class="small text-muted">${esc(b.result).slice(0,150)}${(b.result||'').length>150?'…':''}</p><small class="text-muted"><i class="fas fa-users me-1"></i>${(b.personnel||[]).length} personel <span class="ms-2"><i class="fas fa-robot me-1"></i>${b.ai?'AI':'Manual'}</span></small></div><div class="card-footer bg-light border-0 d-flex justify-content-between"><button class="btn btn-sm btn-link text-success p-0 view-ba" data-id="${esc(b.id)}"><i class="fas fa-eye me-1"></i>Lihat & Cetak</button><span><button class="btn btn-sm btn-light edit-ba" data-id="${esc(b.id)}"><i class="fas fa-pen"></i></button><button class="btn btn-sm btn-light text-danger delete-ba" data-id="${esc(b.id)}"><i class="fas fa-trash"></i></button></span></div></div></div>`).join(''):'<div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body text-center py-5 text-muted"><i class="fas fa-folder-open fa-2x mb-2"></i><p class="mb-0">Tidak ada berita acara yang ditemukan.</p></div></div></div>';}
    let documentationFiles=[];
    function renderDocumentationPreview(){const container=$('ba-documentation-preview');container.innerHTML=documentationFiles.map((image,index)=>`<div class="col-6 col-md-3"><div class="position-relative border rounded p-1 bg-light"><img src="${esc(image.data)}" class="img-fluid rounded" style="height:100px;width:100%;object-fit:cover"><button type="button" class="btn btn-sm btn-danger position-absolute top-0 end-0 m-1 remove-documentation" data-index="${index}" title="Hapus gambar"><i class="fas fa-times"></i></button><div class="small text-truncate mt-1" title="${esc(image.name)}">${esc(image.name)}</div></div></div>`).join('');}
    function readDocumentationFiles(files){return Promise.all([...files].filter(file=>file.type.startsWith('image/')).map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,data:reader.result});reader.onerror=reject;reader.readAsDataURL(file);})));}
    function fillForm(b=null){$('ba-form').reset();documentationFiles=(b?.documentation||[]).map(image=>typeof image==='string'?{name:'Dokumentasi kegiatan',data:image}:image);renderDocumentationPreview();$('ba-id').value=b?.id||'';$('ba-number').value=b?.number||'';$('ba-title').value=b?.title||'';$('ba-status').value=b?.status||'Draft';$('ba-date').value=b?.date||today();$('ba-start').value=b?.start||'';$('ba-end').value=b?.end||'';$('ba-location').value=b?.location||'';$('ba-duration').value=b?.duration||'';$('ba-result').value=b?.result||'';$('ba-notes').value=b?.notes||'';$('ba-tdi-signer').value=b?.tdiSigner||'';$('ba-vendor-signer').value=b?.vendorSigner||'';$('ba-supervisor').value=b?.supervisor||'Iqbal Taufik Akbar';$('ba-personnel-container').innerHTML='';(b?.personnel?.length?b.personnel:[{}]).forEach(x=>$('ba-personnel-container').insertAdjacentHTML('beforeend',personnelHtml(x)));$('ba-timeline-container').innerHTML='';(b?.timeline?.length?b.timeline:[{}]).forEach(x=>$('ba-timeline-container').insertAdjacentHTML('beforeend',timelineHtml(x)));$('ba-ai-panel').classList.add('d-none');$('ba-modal-title').innerHTML=b?'<i class="fas fa-pen me-2"></i>Edit Berita Acara':'<i class="fas fa-file-circle-check me-2"></i>Buat Berita Acara Baru';modal('ba-modal')?.show();}
    function readForm(){return {id:$('ba-id').value||'ba-'+Date.now(),number:$('ba-number').value,title:$('ba-title').value,status:$('ba-status').value,date:$('ba-date').value,start:$('ba-start').value,end:$('ba-end').value,location:$('ba-location').value,duration:$('ba-duration').value,personnel:[...document.querySelectorAll('.ba-personnel-row')].map(r=>({name:r.querySelector('.person-name').value,role:r.querySelector('.person-role').value})),timeline:[...document.querySelectorAll('.ba-timeline-row')].map(r=>({time:r.querySelector('.timeline-time').value,detail:r.querySelector('.timeline-detail').value})),result:$('ba-result').value,notes:$('ba-notes').value,documentation:documentationFiles,tdiSigner:$('ba-tdi-signer').value,vendorSigner:$('ba-vendor-signer').value,supervisor:$('ba-supervisor').value,ai:false};}
    function loadSettings(){[['ba-company-name','companyName'],['ba-company-address','address'],['ba-company-email','email'],['ba-default-dept','defaultDept'],['ba-ai-provider','provider'],['ba-ai-base-url','baseUrl'],['ba-api-key','apiKey'],['ba-ai-model','model']].forEach(([id,k])=>$(id).value=settings[k]||'');$('ba-ai-base-url').value=$('ba-ai-base-url').value||providerDefaults();$('ba-logo-preview').innerHTML=settings.logo?`<img src="${esc(settings.logo)}" style="max-height:70px;max-width:160px">`:'';}
    function providerDefaults(){return $('ba-ai-provider').value==='gemini'?'https://generativelanguage.googleapis.com/v1beta':'https://api.openai.com/v1';}
    function normalizeUrl(url){return (url||'').replace(/\/$/,'');}
    async function aiRequest(prompt){if(!settings.apiKey)throw new Error('API key AI belum diatur. Buka Pengaturan terlebih dahulu.');const provider=settings.provider||'gemini', base=normalizeUrl(settings.baseUrl||providerDefaults()), model=settings.model|| (provider==='gemini'?'gemini-2.0-flash':'gpt-4o-mini');let response;if(provider==='gemini'){response=await fetch(`${base}/models/${model}:generateContent?key=${encodeURIComponent(settings.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});}else{response=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${settings.apiKey}`},body:JSON.stringify({model,messages:[{role:'system',content:'Return valid JSON only.'},{role:'user',content:prompt}],response_format:{type:'json_object'}})});}if(!response.ok)throw new Error(`AI request gagal (${response.status}).`);const data=await response.json();const text=provider==='gemini'?data.candidates?.[0]?.content?.parts?.[0]?.text:data.choices?.[0]?.message?.content;if(!text)throw new Error('AI tidak mengembalikan hasil.');return JSON.parse(text.replace(/^```json\s*|\s*```$/g,''));}
    async function generateAi(){const topic=$('ba-ai-topic').value.trim();if(!topic)return;$('ba-generate-ai').disabled=true;$('ba-ai-status').textContent='AI sedang menyusun berita acara...';try{const data=await aiRequest(`Buat data Berita Acara formal berbahasa Indonesia dari skenario berikut: ${topic}. Kembalikan JSON saja dengan schema: {"number":"","title":"","date":"YYYY-MM-DD","start":"HH:MM","end":"HH:MM","location":"","duration":"","personnel":[{"name":"","role":"IT TDI|Vendor|User Department"}],"timeline":[{"time":"HH:MM","detail":""}],"result":"","notes":"","tdiSigner":"","vendorSigner":"","supervisor":"Iqbal Taufik Akbar"}. Jangan mengarang detail yang tidak ada; gunakan string kosong bila tidak diketahui.`);fillForm({...data,id:'',status:'Draft',ai:true});$('ba-ai-status').textContent='Draft berhasil diisi AI.';}catch(error){$('ba-ai-status').textContent=error.message;}finally{$('ba-generate-ai').disabled=false;}}
    function preview(b){const logo=settings.logo?`<img class="ba-logo" src="${esc(settings.logo)}">`:'<div class="ba-logo d-flex align-items-center"><strong style="font-size:16pt;color:#00529B">TDI</strong></div>',documentation=(b.documentation||[]).map(image=>typeof image==='string'?{name:'Dokumentasi kegiatan',data:image}:image);$('ba-paper').innerHTML=`<div class="ba-header">${logo}<div><div class="ba-company">${esc(settings.companyName)}</div><div class="ba-contact">${esc(settings.address)}<br>${esc(settings.email)}<br>IT Department</div></div></div><h1 class="ba-title">BERITA ACARA</h1><p class="ba-number">Nomor: ${esc(b.number)}</p><table class="ba-detail"><tr><td>Judul Kegiatan</td><td>${esc(b.title)}</td><td>Tanggal</td><td>${esc(formatDate(b.date))}</td></tr><tr><td>Waktu</td><td>${esc(b.start||'-')} - ${esc(b.end||'-')}</td><td>Lokasi</td><td>${esc(b.location)}</td></tr><tr><td>Durasi</td><td>${esc(b.duration||'-')}</td><td>Status</td><td>${esc(b.status)}</td></tr></table><div class="ba-section-title">Personel Pelaksana</div><table class="ba-personnel"><thead><tr><th>No.</th><th>Nama Personel</th><th>Instansi / Peran</th></tr></thead><tbody>${(b.personnel||[]).map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${esc(p.role)}</td></tr>`).join('')}</tbody></table><div class="ba-section-title">Kronologi Kegiatan</div><table class="ba-timeline"><thead><tr><th>Waktu</th><th>Detail Kegiatan</th></tr></thead><tbody>${(b.timeline||[]).map(t=>`<tr><td>${esc(t.time)}</td><td>${esc(t.detail)}</td></tr>`).join('')}</tbody></table><div class="ba-section-title">Hasil Pelaksanaan</div><div class="ba-result">${esc(b.result).replace(/\n/g,'<br>')}</div>${b.notes?`<div class="ba-section-title">Catatan / Tindak Lanjut</div><p>${esc(b.notes).replace(/\n/g,'<br>')}</p>`:''}${documentation.length?`<div class="ba-section-title">Dokumentasi Kegiatan</div><div class="ba-documentation">${documentation.map(image=>`<figure><img src="${esc(image.data)}"><figcaption>${esc(image.name||'Dokumentasi kegiatan')}</figcaption></figure>`).join('')}</div>`:''}<div class="ba-signatures"><div class="ba-signature"><strong>Pelaksana IT TDI</strong><span>( ${esc(b.tdiSigner||'........................')} )</span></div><div class="ba-signature"><strong>Pelaksana Vendor</strong><span>( ${esc(b.vendorSigner||'........................')} )</span></div><div class="ba-signature"><strong>Mengetahui, Supervisor IT</strong><span>( ${esc(b.supervisor||'........................')} )</span></div></div>`;modal('ba-preview-modal')?.show();}
    $('new-ba-btn').addEventListener('click',()=>fillForm());$('ba-settings-btn').addEventListener('click',()=>{loadSettings();modal('ba-settings-modal')?.show();});$('ba-search').addEventListener('input',render);$('ba-status-filter').addEventListener('change',render);$('ba-add-person').addEventListener('click',()=>{$('ba-personnel-container').insertAdjacentHTML('beforeend',personnelHtml());});$('ba-add-timeline').addEventListener('click',()=>{$('ba-timeline-container').insertAdjacentHTML('beforeend',timelineHtml());});$('ba-toggle-ai').addEventListener('click',()=>{$('ba-ai-panel').classList.toggle('d-none');if(!$('ba-ai-panel').classList.contains('d-none'))$('ba-ai-topic').focus();});$('ba-generate-ai').addEventListener('click',generateAi);$('ba-print').addEventListener('click',()=>window.print());$('ba-download-pdf').addEventListener('click',()=>{if(typeof html2pdf==='undefined')return alert('Library PDF belum termuat. Gunakan Print lalu pilih Save as PDF.');const paper=$('ba-paper');paper.classList.add('ba-export');html2pdf().set({margin:[18,18,22,18],filename:`Berita_Acara_${$('ba-number').value||'Official'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},pagebreak:{mode:['css','legacy'],avoid:['.ba-detail','.ba-result','.ba-signatures']},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(paper).save().catch(error=>alert(`Gagal membuat PDF: ${error.message}`)).finally(()=>paper.classList.remove('ba-export'));});
    $('ba-form').addEventListener('submit',e=>{e.preventDefault();const b=readForm(),i=bas.findIndex(x=>x.id===b.id);if(i<0)bas.unshift(b);else bas[i]=b;persist();render();modal('ba-modal')?.hide();});$('ba-settings-form').addEventListener('submit',async e=>{e.preventDefault();Object.assign(settings,{companyName:$('ba-company-name').value,address:$('ba-company-address').value,email:$('ba-company-email').value,defaultDept:$('ba-default-dept').value,provider:$('ba-ai-provider').value,baseUrl:normalizeUrl($('ba-ai-base-url').value)||providerDefaults(),apiKey:$('ba-api-key').value.trim(),model:$('ba-ai-model').value});settings=await saveAdminSettings(settings);modal('ba-settings-modal')?.hide();});$('ba-ai-provider').addEventListener('change',()=>{$('ba-ai-base-url').value=providerDefaults();$('ba-ai-model').innerHTML='<option value="">Load model terlebih dahulu</option>';});$('ba-company-logo').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{settings.logo=r.result;$('ba-logo-preview').innerHTML=`<img src="${esc(r.result)}" style="max-height:70px;max-width:160px">`};r.readAsDataURL(f);});
    $('ba-documentation-files').addEventListener('change',async e=>{try{documentationFiles.push(...await readDocumentationFiles(e.target.files));renderDocumentationPreview();e.target.value='';}catch(error){alert(`Gagal membaca gambar: ${error.message}`);}});$('ba-documentation-preview').addEventListener('click',e=>{const button=e.target.closest('.remove-documentation');if(!button)return;documentationFiles.splice(Number(button.dataset.index),1);renderDocumentationPreview();});$('ba-personnel-container').addEventListener('click',e=>{if(e.target.closest('.remove-person'))e.target.closest('.ba-personnel-row').remove();});$('ba-timeline-container').addEventListener('click',e=>{if(e.target.closest('.remove-timeline'))e.target.closest('.ba-timeline-row').remove();});$('ba-grid').addEventListener('click',e=>{const id=e.target.closest('[data-id]')?.dataset.id,b=bas.find(x=>x.id===id);if(!b)return;if(e.target.closest('.view-ba'))preview(b);if(e.target.closest('.edit-ba'))fillForm(b);if(e.target.closest('.delete-ba')&&confirm('Hapus berita acara ini?')){bas=bas.filter(x=>x.id!==id);persist();render();}});$('ba-reset-data').addEventListener('click',()=>{if(confirm('Reset seluruh berita acara ke data sample?')){bas=[JSON.parse(JSON.stringify(sample))];persist();render();}});render();
});
</script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const button=document.getElementById('ba-load-ai-models');
    if(!button)return;
    button.addEventListener('click',async()=>{
        const provider=document.getElementById('ba-ai-provider').value;
        const base=(document.getElementById('ba-ai-base-url').value||'').replace(/\/$/,'');
        const apiKey=document.getElementById('ba-api-key').value.trim();
        const status=document.getElementById('ba-ai-model-status');
        if(!apiKey){status.textContent='Masukkan API key terlebih dahulu.';return;}
        button.disabled=true; status.textContent='Memuat model...';
        try{
            const response=provider==='gemini'
                ?await fetch(`${base}/models?key=${encodeURIComponent(apiKey)}`)
                :await fetch(`${base}/models`,{headers:{Accept:'application/json',Authorization:`Bearer ${apiKey}`}});
            if(!response.ok){const text=await response.text();let message=text;try{const payload=JSON.parse(text);message=payload?.error?.message||payload?.message||payload?.detail||text;}catch{}throw new Error(`Gagal memuat model (${response.status}): ${message.slice(0,180)}`);}
            const data=await response.json();
            const source=provider==='gemini'?(data.models||[]):(Array.isArray(data)?data:data.data||data.models||data.result?.data||data.result?.models||data.result||[]);
            const models=(Array.isArray(source)?source:[]).filter(model=>provider!=='gemini'||(model.supportedGenerationMethods||[]).includes('generateContent'));
            if(!models.length)throw new Error('Provider tidak mengembalikan model yang dapat digunakan.');
            const select=document.getElementById('ba-ai-model');
            const selected=select.value;
            select.innerHTML=models.map(model=>{const name=(typeof model==='string'?model:model.name||model.id||model.model||'').replace(/^models\//,'');return name?`<option value="${name.replace(/"/g,'&quot;')}">${name}</option>`:'';}).join('');
            select.value=[...select.options].some(option=>option.value===selected)?selected:select.options[0].value;
            status.textContent=`${models.length} model tersedia.`;
        }catch(error){status.textContent=`${error.message}${error instanceof TypeError?' Periksa Base URL dan CORS endpoint.':''}`;}finally{button.disabled=false;}
    });
});
</script>
@endsection