@extends('layouts.admin')

@section('title', 'Memo Maker')
@section('page-title', 'Memo Maker')

@section('content')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
    .memo-card { transition: transform .15s ease, box-shadow .15s ease; }
    .memo-card:hover { transform: translateY(-2px); box-shadow: 0 .5rem 1rem rgba(30,58,95,.12)!important; }
    .memo-paper { width:100%; max-width:210mm; min-height:297mm; box-sizing:border-box; margin:auto; background:#fff; padding:20mm 22mm 25mm; font-family:Arial,sans-serif; color:#282828; font-size:10.5pt; line-height:1.45; overflow-wrap:anywhere; }
    .memo-paper .memo-header { display:flex; justify-content:space-between; align-items:flex-end; border-bottom:1pt solid #00529B; padding-bottom:8pt; }
    .memo-paper .memo-logo { height:42pt; max-width:150pt; object-fit:contain; }
    .memo-paper .memo-company { margin-top:5pt; font-size:10pt; font-weight:700; letter-spacing:.5pt; text-transform:uppercase; color:#282828; }
    .memo-paper .memo-contact { max-width:230pt; text-align:right; font-size:8.75pt; line-height:1.2; color:#4A5568; }
    .memo-paper .memo-title { margin:18pt 0 14pt; text-align:center; font-size:16pt; font-weight:700; letter-spacing:2pt; color:#000; }
    .memo-paper .memo-meta { width:100%; margin-bottom:14pt; border-collapse:collapse; background:#F5F7FA; font-size:10pt; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-meta td { padding:4pt 7pt; vertical-align:top; }
    .memo-paper .memo-meta td:first-child { width:2.8cm; font-weight:700; color:#282828; }
    .memo-paper .memo-meta tr:last-child td:last-child { color:#00529B; font-weight:700; }
    .memo-paper .memo-intro { margin:0 0 6pt; color:#282828; break-inside:avoid; page-break-inside:avoid; orphans:3; widows:3; }
    .memo-paper .memo-callout { margin:12pt 0; padding:8pt 12pt; border:1pt solid #00529B; border-radius:4pt; background:#fff; font-size:9.5pt; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-callout-title { display:block; margin-bottom:3pt; color:#00529B; font-size:10pt; font-weight:700; text-transform:uppercase; }
    .memo-paper .memo-callout ol { margin:3pt 0 0 1.5em; padding:0; }
    .memo-paper .memo-section-title { margin:12pt 0 7pt; padding-bottom:3pt; border-bottom:1pt solid #00529B; color:#00529B; font-size:12pt; font-weight:700; line-height:1.25; text-transform:uppercase; break-after:avoid; page-break-after:avoid; }
    .memo-paper .memo-step { margin:12pt 0 14pt; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-step-title { margin:0 0 4pt; color:#282828; font-size:11pt; font-weight:700; }
    .memo-paper .memo-step-desc { margin:0; color:#333; font-size:10pt; line-height:1.4; white-space:pre-line; }
    .memo-paper .memo-step-image { display:block; max-width:100%; max-height:240pt; margin:7pt auto 0; object-fit:contain; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-notes { margin-top:14pt; padding-top:8pt; border-top:1pt solid #D2D7E1; font-size:9.5pt; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-notes-title { color:#00529B; font-size:10pt; font-weight:700; text-transform:uppercase; }
    .memo-paper .memo-notes ul { margin:3pt 0 0 1.5em; padding:0; }
    .memo-paper .memo-signature { margin-top:20pt; text-align:right; font-size:10.5pt; color:#000; break-inside:avoid; page-break-inside:avoid; }
    .memo-paper .memo-signature p { margin:0 0 4pt; }
    .step-row { border-left:4px solid #1e3a5f; }
    #memo-modal .modal-dialog { height: calc(100% - 1rem); }
    #memo-modal .modal-content { height: 100%; }
    #memo-modal form { display: flex; flex: 1 1 auto; min-height: 0; flex-direction: column; }
    #memo-modal .modal-body { overflow-y: auto; min-height: 0; }
    #memo-modal .modal-footer { flex-shrink: 0; }
    #settings-modal .modal-dialog { height: calc(100% - 1rem); max-height: calc(100% - 1rem); }
    #settings-modal .modal-content { height: 100%; max-height: 100%; }
    #settings-modal form { display: flex; flex: 1 1 auto; min-height: 0; flex-direction: column; }
    #settings-modal .modal-body { overflow-y: auto; min-height: 0; }
    #settings-modal .modal-footer { flex-shrink: 0; }
    .memo-paper.memo-export { width:166mm; max-width:166mm; padding:0; min-height:0; margin:0; }
    @media print { @page { size:A4 portrait; margin:20mm 22mm 25mm; } html, body { margin:0!important; padding:0!important; width:100%!important; overflow:visible!important; } body * { visibility:hidden!important; } #preview-modal, #preview-modal .modal-dialog, #preview-modal .modal-content, #preview-modal .modal-body { display:block!important; position:static!important; width:100%!important; max-width:none!important; height:auto!important; min-height:0!important; margin:0!important; padding:0!important; border:0!important; overflow:visible!important; box-shadow:none!important; } #memo-paper, #memo-paper * { visibility:visible!important; } #memo-paper { position:static; width:100%!important; max-width:none!important; min-height:0; padding:0; margin:0; box-shadow:none!important; overflow:visible!important; } .no-print { display:none!important; } }
</style>

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h4 class="mb-1 font-headline"><i class="fas fa-file-signature text-primary me-2"></i>Memo Maker</h4><p class="text-muted mb-0">Buat memo internal resmi dan panduan teknis untuk kebutuhan IT.</p></div>
    <div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="settings-btn"><i class="fas fa-gear me-1"></i>Pengaturan</button><button class="btn btn-primary" id="new-memo-btn"><i class="fas fa-plus me-1"></i>Memo Baru</button></div>
</div>

<div class="card shadow-sm border-0 mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-md-8"><div class="input-group"><span class="input-group-text bg-white"><i class="fas fa-search"></i></span><input id="memo-search" class="form-control" placeholder="Cari nomor, perihal, atau tujuan memo..."></div></div><div class="col-md-4 text-md-end"><span class="text-muted small" id="memo-count">Total: 0 memo</span><button class="btn btn-sm btn-link text-danger ms-2" id="reset-data">Reset sample</button></div></div></div></div>
<div id="memo-grid" class="row g-4"></div>

<div class="modal fade" id="document-type-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-file-circle-plus text-primary me-2"></i>Dokumen Baru</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body"><p class="text-muted small mb-3">Pilih jenis dokumen yang ingin dibuat.</p><div class="row g-3"><div class="col-md-6"><button type="button" class="btn btn-outline-primary w-100 text-start p-3 document-type-choice" data-document="memo"><i class="fas fa-file-signature fa-lg me-2"></i><strong>Buat Memo</strong><small class="d-block text-muted mt-1">Memo internal dan panduan teknis</small></button></div><div class="col-md-6"><button type="button" class="btn btn-outline-success w-100 text-start p-3 document-type-choice" data-document="ba"><i class="fas fa-file-circle-check fa-lg me-2"></i><strong>Buat Berita Acara</strong><small class="d-block text-muted mt-1">Dokumentasi formal kegiatan operasional</small></button></div></div></div></div></div></div>

{{-- Create/edit modal --}}
<div class="modal fade" id="memo-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-primary text-white"><h5 class="modal-title" id="memo-modal-title"><i class="fas fa-file-signature me-2"></i>Buat Memo Baru</h5><div class="d-flex align-items-center gap-2"><button type="button" class="btn btn-sm btn-light text-primary" id="toggle-ai"><i class="fas fa-wand-magic-sparkles me-1"></i>AI Auto-Fill</button><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Tutup"></button></div></div><form id="memo-form"><div class="modal-body">
    <div id="ai-panel" class="alert alert-primary d-none"><div class="d-flex justify-content-between align-items-center mb-2"><strong><i class="fas fa-robot me-1"></i>Gemini AI Memo Generator</strong><small>Masukkan topik atau ringkasan teknis</small></div><div class="input-group input-group-sm"><input id="ai-topic" class="form-control" placeholder="Contoh: Panduan setting VPN Cisco AnyConnect untuk WFH"><button type="button" class="btn btn-primary" id="generate-ai"><i class="fas fa-sparkles me-1"></i>Generate Draft</button></div><div id="ai-status" class="small mt-2 d-none"></div></div>
    <input type="hidden" id="memo-id">
    <div class="row g-3 mb-4"><div class="col-md-6"><label class="form-label">Nomor Memo</label><input id="no-memo" class="form-control" required placeholder="06/MM-IT-TDI/VIII/26"></div><div class="col-md-6"><label class="form-label">Tanggal</label><input id="memo-date" class="form-control" required></div><div class="col-md-6"><label class="form-label">Kepada</label><input id="memo-to" class="form-control" required placeholder="Seluruh Karyawan"></div><div class="col-md-6"><label class="form-label">Dari</label><input id="memo-from" class="form-control" required></div><div class="col-12"><label class="form-label">Perihal / Subjek</label><input id="memo-subject" class="form-control" required></div><div class="col-12"><div class="d-flex justify-content-between align-items-center"><label class="form-label mb-1">Paragraf Pembuka / Pengantar</label><button type="button" class="btn btn-sm btn-link text-primary p-0" id="polish-intro"><i class="fas fa-wand-magic-sparkles me-1"></i>Perbaiki Bahasa dengan AI</button></div><textarea id="memo-intro" rows="3" class="form-control" required></textarea></div></div>
    <div class="p-3 rounded border bg-light mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><label class="fw-semibold text-primary mb-0"><i class="fas fa-clipboard-check me-1"></i>Alur Permohonan & Persyaratan Akses</label><div class="form-check"><input id="show-reqs" class="form-check-input" type="checkbox" checked><label class="form-check-label small" for="show-reqs">Tampilkan</label></div></div><input id="req-1" class="form-control form-control-sm mb-2" placeholder="Pengajuan akses oleh PIC department..."><input id="req-2" class="form-control form-control-sm" placeholder="Konfirmasi IT dan instruksi akses..."></div>
    <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-3"><div><h6 class="mb-1 fw-bold"><i class="fas fa-list-ol text-primary me-2"></i>Langkah-Langkah Teknis</h6><small class="text-muted">Tambahkan screenshot atau gambar pada setiap langkah.</small></div><button type="button" class="btn btn-sm btn-outline-primary" id="add-step"><i class="fas fa-plus me-1"></i>Tambah Langkah</button></div><div id="steps-container"></div>
    <div class="p-3 rounded border bg-light mt-4"><label class="form-label fw-semibold">Catatan Penting & Ketentuan Keamanan</label><input id="note-1" class="form-control form-control-sm mb-2" placeholder="Pastikan terhubung ke jaringan kantor atau VPN..."><input id="note-2" class="form-control form-control-sm mb-2" placeholder="Dilarang membagikan data login..."><input id="note-3" class="form-control form-control-sm" placeholder="Hubungi IT Support jika mengalami kendala..."></div>
</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary"><i class="fas fa-save me-1"></i>Simpan Memo</button></div></form></div></div></div>

{{-- Settings modal --}}<div class="modal fade" id="settings-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-building text-primary me-2"></i>Pengaturan Kop Surat & AI</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><form id="settings-form"><div class="modal-body"><label class="form-label">Nama Perusahaan</label><input id="company-name" class="form-control mb-3" required><label class="form-label">Alamat Kantor</label><textarea id="company-address" rows="2" class="form-control mb-3" required></textarea><label class="form-label">Email IT Support</label><input id="company-email" type="email" class="form-control mb-3" required><label class="form-label">Default Pengirim</label><input id="default-dept" class="form-control mb-3" required><div class="p-3 rounded border border-primary-subtle bg-primary-subtle mb-3"><label class="form-label fw-semibold">Provider AI</label><select id="ai-provider" class="form-select form-select-sm mb-2"><option value="gemini">Gemini API</option><option value="openai">OpenAI-compatible</option></select><label class="form-label small">Base URL</label><input id="ai-base-url" class="form-control form-control-sm mb-2" placeholder="https://generativelanguage.googleapis.com/v1beta"><label class="form-label small">API Key</label><input id="gemini-key" type="password" class="form-control form-control-sm mb-2" placeholder="Masukkan API key"><div class="input-group input-group-sm mb-2"><select id="ai-model" class="form-select"><option value="">Load model terlebih dahulu</option></select><button type="button" class="btn btn-outline-primary" id="load-ai-models"><i class="fas fa-rotate me-1"></i>Load Models</button></div><div id="ai-model-status" class="small text-muted">Model akan dimuat dari provider yang dipilih.</div><small class="text-muted d-block mt-2">Konfigurasi disimpan di localStorage browser dan request dikirim langsung ke provider.</small></div><label class="form-label">Logo (opsional)</label><input id="company-logo" type="file" accept="image/*" class="form-control form-control-sm"><div id="logo-preview" class="mt-2"></div></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Simpan Pengaturan</button></div></form></div></div></div>

<div class="modal fade" id="preview-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-dark text-white no-print"><h5 class="modal-title"><i class="fas fa-eye text-info me-2"></i>Pratinjau Memo Official</h5><div><button id="print-memo" class="btn btn-sm btn-outline-light me-2"><i class="fas fa-print me-1"></i>Print</button><button id="download-pdf" class="btn btn-sm btn-success me-2"><i class="fas fa-file-pdf me-1"></i>Download PDF</button><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div></div><div class="modal-body bg-secondary-subtle p-3 p-md-5"><div id="memo-paper" class="memo-paper shadow"></div></div></div></div></div>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const memoKey='tdi_admin_memos_v1', settingsKey='tdi_admin_memo_settings_v1';
    const defaults={companyName:'PT. TERA DATA INDONUSA Tbk.',address:'Jl. Inspeksi Pam No.168 17, RT.17/RW.4, Cakung, Jakarta 13910',email:'it.support@terra.co.id',defaultDept:'IT Department',logo:'',provider:'gemini',baseUrl:'https://generativelanguage.googleapis.com/v1beta',apiKey:'',model:''};
    const sample={id:'memo-1',noMemo:'06/MM-IT-TDI/VIII/26',tanggal:'24 Agustus 2026',kepada:'Seluruh Karyawan / Pengguna NAS PT Tera Data Indonusa Tbk',dari:'IT Department',perihal:'Panduan Pemetaan Network Attached Storage (NAS)',intro:'Sehubungan dengan standarisasi tata kelola penyimpanan data internal, bersama ini IT Department menyampaikan panduan teknis pemetaan lokasi penyimpanan jaringan NAS.',showReqs:true,req1:'PIC department mengajukan permohonan akses folder NAS ke IT melalui email resmi.',req2:'Setelah akses diberikan IT, ikuti instruksi pemetaan berikut.',steps:[{title:'Langkah 1: Membuka File Explorer',desc:'Buka File Explorer dengan menekan Win + E, pilih This PC, lalu klik Map network drive.',image:''},{title:'Langkah 2: Memilih Drive dan Folder NAS',desc:'Pilih drive yang tersedia, masukkan alamat folder NAS, dan centang Reconnect at sign-in.',image:''}],notes:['Pastikan perangkat terhubung ke Wi-Fi/LAN kantor atau VPN resmi perusahaan.','Dilarang membagikan username dan password kepada pihak lain.','Hubungi IT Support jika mengalami kendala.']};
    const legacySettings=JSON.parse(localStorage.getItem(settingsKey)||'{}');
    let memos=JSON.parse(localStorage.getItem(memoKey)||'null')||[sample], settings={...defaults,...legacySettings,...@json($adminSettings ?? [])};
    if(!settings.apiKey&&settings.geminiApiKey)settings.apiKey=settings.geminiApiKey;
    const $=id=>document.getElementById(id), modal=id=>window.bootstrap?.Modal.getOrCreateInstance($(id));
    const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const persist=()=>localStorage.setItem(memoKey,JSON.stringify(memos));
    const dateNow=()=>new Date().toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});

    function render(){const query=($('memo-search').value||'').toLowerCase();const list=memos.filter(m=>[m.noMemo,m.perihal,m.kepada].some(v=>(v||'').toLowerCase().includes(query)));$('memo-count').textContent=`Total: ${list.length} memo`; $('memo-grid').innerHTML=list.length?list.map(m=>`<div class="col-12 col-md-6 col-xl-4"><div class="card memo-card h-100 shadow-sm border-0"><div class="card-body"><div class="d-flex justify-content-between gap-2 mb-3"><span class="badge text-bg-primary">${esc(m.noMemo)}</span><small class="text-muted">${esc(m.tanggal)}</small></div><h5 class="card-title fs-6 fw-bold">${esc(m.perihal)}</h5><p class="small mb-2"><strong>Kepada:</strong> ${esc(m.kepada)}</p><p class="small text-muted">${esc(m.intro).slice(0,150)}${m.intro.length>150?'…':''}</p><small class="text-muted"><i class="fas fa-list-ol me-1"></i>${(m.steps||[]).length} langkah penjelasan</small></div><div class="card-footer bg-light border-0 d-flex justify-content-between"><button class="btn btn-sm btn-link text-primary p-0 view-memo" data-id="${esc(m.id)}"><i class="fas fa-eye me-1"></i>Lihat & Cetak</button><span><button class="btn btn-sm btn-light edit-memo" data-id="${esc(m.id)}"><i class="fas fa-pen"></i></button><button class="btn btn-sm btn-light text-danger delete-memo" data-id="${esc(m.id)}"><i class="fas fa-trash"></i></button></span></div></div></div>`).join(''):'<div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body text-center py-5 text-muted"><i class="fas fa-folder-open fa-2x mb-2"></i><p class="mb-0">Tidak ada memo yang ditemukan.</p></div></div></div>';}
    function stepHtml(step={}){return `<div class="step-row border rounded p-3 mb-3 bg-light-subtle"><div class="d-flex justify-content-between mb-2"><strong class="small">Langkah teknis</strong><button type="button" class="btn btn-sm btn-link text-danger remove-step">Hapus</button></div><input class="form-control form-control-sm step-title mb-2" required placeholder="Judul langkah" value="${esc(step.title)}"><textarea class="form-control form-control-sm step-desc mb-2" required rows="2" placeholder="Penjelasan teknis">${esc(step.desc)}</textarea><input type="file" accept="image/*" class="form-control form-control-sm step-image"><input type="hidden" class="step-image-data" value="${esc(step.image)}"><div class="step-preview mt-2">${step.image?`<img src="${esc(step.image)}" class="img-thumbnail" style="max-height:110px">`:''}</div></div>`;}
    function fillForm(m=null){$('memo-form').reset();$('ai-panel').classList.add('d-none');$('memo-id').value=m?.id||'';$('no-memo').value=m?.noMemo||'';$('memo-date').value=m?.tanggal||dateNow();$('memo-to').value=m?.kepada||'';$('memo-from').value=m?.dari||settings.defaultDept;$('memo-subject').value=m?.perihal||'';$('memo-intro').value=m?.intro||'';$('show-reqs').checked=m?.showReqs!==false;$('req-1').value=m?.req1||'';$('req-2').value=m?.req2||'';['note-1','note-2','note-3'].forEach((id,i)=>$(id).value=m?.notes?.[i]||'');$('steps-container').innerHTML='';(m?.steps?.length?m.steps:[{}]).forEach(s=>$('steps-container').insertAdjacentHTML('beforeend',stepHtml(s)));$('memo-modal-title').innerHTML=m?'<i class="fas fa-pen me-2"></i>Edit Memo':'<i class="fas fa-file-pen me-2"></i>Buat Memo Baru';modal('memo-modal')?.show();}
    function readForm(){return {id:$('memo-id').value||'memo-'+Date.now(),noMemo:$('no-memo').value,tanggal:$('memo-date').value,kepada:$('memo-to').value,dari:$('memo-from').value,perihal:$('memo-subject').value,intro:$('memo-intro').value,showReqs:$('show-reqs').checked,req1:$('req-1').value,req2:$('req-2').value,steps:[...document.querySelectorAll('.step-row')].map(r=>({title:r.querySelector('.step-title').value,desc:r.querySelector('.step-desc').value,image:r.querySelector('.step-image-data').value})),notes:['note-1','note-2','note-3'].map(id=>$(id).value).filter(Boolean)};}
    function preview(m){const logo=settings.logo?`<img src="${esc(settings.logo)}" class="memo-logo">`:'<strong class="memo-logo" style="display:inline-block;font-size:18pt;color:#00529B">TDI</strong>';const req=m.showReqs&&(m.req1||m.req2)?`<div class="memo-callout"><strong class="memo-callout-title">Alur Permohonan & Persyaratan Akses</strong><ol>${m.req1?`<li>${esc(m.req1)}</li>`:''}${m.req2?`<li>${esc(m.req2)}</li>`:''}</ol></div>`:'';const steps=(m.steps||[]).map((s,i)=>`<div class="memo-step"><h4 class="memo-step-title">${i+1}. ${esc(s.title)}</h4><p class="memo-step-desc">${esc(s.desc)}</p>${s.image?`<img src="${esc(s.image)}" class="memo-step-image">`:''}</div>`).join('');const notes=m.notes?.length?`<div class="memo-notes"><strong class="memo-notes-title">Catatan Penting & Ketentuan Keamanan</strong><ul>${m.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div>`:'';$('memo-paper').innerHTML=`<header class="memo-header"><div>${logo}<div class="memo-company">${esc(settings.companyName)}</div></div><div class="memo-contact">${esc(settings.address)}<br>Email: ${esc(settings.email)}</div></header><h2 class="memo-title">MEMORANDUM</h2><table class="memo-meta"><tbody><tr><td>Kepada</td><td>${esc(m.kepada)}</td></tr><tr><td>Dari</td><td>${esc(m.dari)}</td></tr><tr><td>Tanggal</td><td>${esc(m.tanggal)}</td></tr><tr><td>No. Memo</td><td>${esc(m.noMemo)}</td></tr><tr><td>Perihal</td><td>${esc(m.perihal)}</td></tr></tbody></table><p class="memo-intro">${esc(m.intro)}</p>${req}<h3 class="memo-section-title">Panduan Langkah-Langkah Teknis</h3>${steps}${notes}<div class="memo-signature"><p>Jakarta, ${esc(m.tanggal)}</p><p style="margin-bottom:65pt">Hormat Kami,</p><strong>${esc(m.dari)}</strong><br>${esc(settings.companyName)}</div>`;modal('preview-modal').show();}
    function providerDefaults(){return $('ai-provider').value==='openai'?'https://api.openai.com/v1':'https://generativelanguage.googleapis.com/v1beta';}
    function loadSettings(){['company-name','company-address','company-email','default-dept'].forEach((id,i)=>$(id).value=[settings.companyName,settings.address,settings.email,settings.defaultDept][i]);$('ai-provider').value=settings.provider||'gemini';$('ai-base-url').value=settings.baseUrl||providerDefaults();$('gemini-key').value=settings.apiKey||settings.geminiApiKey||'';$('ai-model').innerHTML=settings.model?`<option value="${esc(settings.model)}">${esc(settings.model)}</option>`:'<option value="">Load model terlebih dahulu</option>';$('ai-model').value=settings.model||'';$('logo-preview').innerHTML=settings.logo?`<img src="${esc(settings.logo)}" style="max-height:70px;max-width:160px">`:'';}
    function setAiStatus(message,error=false){$('ai-status').textContent=message;$('ai-status').classList.toggle('text-danger',error);$('ai-status').classList.remove('d-none');}
    function normalizeBaseUrl(url){return (url||'').trim().replace(/\s+/g,'').replace(/\/+$/,'');}
    function extractText(data){return data.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('')||data.choices?.[0]?.message?.content||'';}
    async function loadAiModels(){const provider=$('ai-provider').value,baseUrl=normalizeBaseUrl($('ai-base-url').value)||providerDefaults(),key=$('gemini-key').value.trim(),status=$('ai-model-status'),button=$('load-ai-models');if(!key){status.textContent='API key wajib diisi.';status.className='small text-danger';return;}button.disabled=true;status.textContent='Memuat daftar model...';try{const isOpenAi=provider==='openai',url=isOpenAi?`${baseUrl}/models`:`${baseUrl}/models?key=${encodeURIComponent(key)}`,response=await fetch(url,{headers:isOpenAi?{Accept:'application/json',Authorization:`Bearer ${key}`}:{Accept:'application/json'}}),raw=await response.text();let data;try{data=raw?JSON.parse(raw):{};}catch{throw new Error(`Respons model bukan JSON (HTTP ${response.status}): ${raw.slice(0,180)}`);}if(!response.ok)throw new Error(data.error?.message||data.message||data.detail||`HTTP ${response.status}`);const source=isOpenAi?(Array.isArray(data)?data:data.data||data.models||data.result?.data||data.result?.models||data.result||[]):(Array.isArray(data)?data:data.models||data.data||[]),items=Array.isArray(source)?source:[];const models=items.map(item=>typeof item==='string'?item:item?.id||item?.name||item?.model).map(id=>id?.replace(/^models\//,'')).filter(Boolean).filter((id,index,list)=>list.indexOf(id)===index);if(!models.length)throw new Error(`Provider mengembalikan respons tanpa model (HTTP ${response.status}).`);$('ai-model').innerHTML=models.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('');$('ai-model').value=models.includes(settings.model)?settings.model:models[0];status.textContent=`${models.length} model tersedia.`;status.className='small text-success';}catch(error){status.textContent=`Gagal memuat model: ${error.message||'Request gagal'}${error instanceof TypeError?' Periksa Base URL dan CORS endpoint.':''}`;status.className='small text-danger';}finally{button.disabled=false;}}
    async function geminiRequest(prompt,responseSchema=null){const provider=settings.provider||'gemini',baseUrl=normalizeBaseUrl(settings.baseUrl)||providerDefaults(),key=settings.apiKey||settings.geminiApiKey||'',model=settings.model||'';if(!key)throw new Error('API key belum diisi. Buka Pengaturan terlebih dahulu.');if(!model)throw new Error('Model AI belum dipilih. Buka Pengaturan lalu Load Models.');let response,payload;if(provider==='openai'){payload={model,messages:[{role:'user',content:prompt}],temperature:.4};if(responseSchema)payload.response_format={type:'json_object'};response=await fetch(`${baseUrl}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify(payload)});}else{payload={contents:[{parts:[{text:prompt}]}]};if(responseSchema)payload.generationConfig={responseMimeType:'application/json',responseSchema};response=await fetch(`${baseUrl}/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`${provider==='openai'?'OpenAI-compatible':'Gemini'} HTTP ${response.status}: ${data.error?.message||'Request gagal'}`);const text=extractText(data);if(!text)throw new Error('Respons AI kosong.');return text;}
    async function generateAiMemo(){const topic=$('ai-topic').value.trim();if(!topic)return setAiStatus('Masukkan topik memo terlebih dahulu.',true);const button=$('generate-ai');button.disabled=true;setAiStatus('Gemini sedang menyusun draft memo...');try{const text=await geminiRequest(`Anda adalah technical writer senior PT Tera Data Indonusa Tbk. Buat draft memo internal teknis berbahasa Indonesia untuk topik: "${topic}". Buat ringkas tetapi lengkap dan profesional.`,{type:'OBJECT',properties:{noMemo:{type:'STRING'},perihal:{type:'STRING'},kepada:{type:'STRING'},intro:{type:'STRING'},req1:{type:'STRING'},req2:{type:'STRING'},steps:{type:'ARRAY',items:{type:'OBJECT',properties:{title:{type:'STRING'},desc:{type:'STRING'}},required:['title','desc']}},notes:{type:'ARRAY',items:{type:'STRING'}}},required:['perihal','kepada','intro','steps','notes']});const draft=JSON.parse(text);if(draft.noMemo)$('no-memo').value=draft.noMemo;if(draft.perihal)$('memo-subject').value=draft.perihal;if(draft.kepada)$('memo-to').value=draft.kepada;if(draft.intro)$('memo-intro').value=draft.intro;if(draft.req1)$('req-1').value=draft.req1;if(draft.req2)$('req-2').value=draft.req2;if(draft.steps?.length){$('steps-container').innerHTML='';draft.steps.forEach(s=>$('steps-container').insertAdjacentHTML('beforeend',stepHtml(s)));}draft.notes?.slice(0,3).forEach((note,i)=>$(`note-${i+1}`).value=note);setAiStatus('Draft memo berhasil dibuat. Silakan review sebelum disimpan.');}catch(error){setAiStatus(error.message,true);}finally{button.disabled=false;}}
    async function polishIntro(){const text=$('memo-intro').value.trim();if(!text)return;try{$('memo-intro').disabled=true;$('memo-intro').value=(await geminiRequest(`Rapikan teks berikut menjadi bahasa memo perusahaan yang baku, singkat, profesional, dan mudah dipahami. Kembalikan hanya teks hasil revisi:\n\n${text}`)).trim();}catch(error){alert(error.message);}finally{$('memo-intro').disabled=false;}}
    $('new-memo-btn').addEventListener('click',()=>modal('document-type-modal')?.show());
    document.querySelectorAll('.document-type-choice').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.document==='ba'){window.location.href='{{ route('admin.berita-acara-maker.index') }}';return;}modal('document-type-modal')?.hide();fillForm();}));
    $('settings-btn').addEventListener('click',()=>{loadSettings();modal('settings-modal')?.show();});
    $('memo-search').addEventListener('input',render);
    $('add-step').addEventListener('click',()=>{$('steps-container').insertAdjacentHTML('beforeend',stepHtml());$('steps-container').lastElementChild?.querySelector('.step-title')?.focus();});
    $('print-memo').addEventListener('click',()=>window.print());
    $('download-pdf').addEventListener('click',()=>{if(typeof html2pdf==='undefined')return alert('Library PDF belum termuat. Gunakan Print lalu pilih Save as PDF.');const paper=$('memo-paper');paper.classList.add('memo-export');html2pdf().set({margin:[20,22,25,22],filename:`Memo_${$('no-memo').value||'Official'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},pagebreak:{mode:['css','legacy'],avoid:['.memo-meta','.memo-intro','.memo-callout','.memo-step','.memo-notes','.memo-signature']},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(paper).save().catch(error=>alert(`Gagal membuat PDF: ${error.message}`)).finally(()=>paper.classList.remove('memo-export'));});
    $('toggle-ai').addEventListener('click',()=>{$('ai-panel').classList.toggle('d-none');if(!$('ai-panel').classList.contains('d-none'))$('ai-topic').focus();});
    $('generate-ai').addEventListener('click',generateAiMemo);
    $('polish-intro').addEventListener('click',polishIntro);
    $('memo-form').addEventListener('submit',e=>{e.preventDefault();const m=readForm(),i=memos.findIndex(x=>x.id===m.id);i<0?memos.unshift(m):memos[i]=m;persist();render();modal('memo-modal')?.hide();});
    $('settings-form').onsubmit=async e=>{e.preventDefault();Object.assign(settings,{companyName:$('company-name').value,address:$('company-address').value,email:$('company-email').value,defaultDept:$('default-dept').value,provider:$('ai-provider').value,baseUrl:normalizeBaseUrl($('ai-base-url').value)||providerDefaults(),apiKey:$('gemini-key').value.trim(),model:$('ai-model').value,geminiApiKey:$('ai-provider').value==='gemini'?$('gemini-key').value.trim():settings.geminiApiKey||''});settings=await saveAdminSettings(settings);modal('settings-modal').hide();};
    $('ai-provider').addEventListener('change',()=>{$('ai-base-url').value=providerDefaults();$('ai-model').innerHTML='<option value="">Load model terlebih dahulu</option>';$('ai-model-status').textContent='Klik Load Models untuk mengambil model provider.';$('ai-model-status').className='small text-muted';});
    $('load-ai-models').addEventListener('click',loadAiModels);
    $('company-logo').onchange=e=>{const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>{settings.logo=r.result;$('logo-preview').innerHTML=`<img src="${esc(r.result)}" style="max-height:70px;max-width:160px">`};r.readAsDataURL(f);}};
    $('steps-container').addEventListener('click',e=>{if(e.target.closest('.remove-step'))e.target.closest('.step-row').remove();});$('steps-container').addEventListener('change',e=>{if(!e.target.matches('.step-image'))return;const r=new FileReader(),row=e.target.closest('.step-row');r.onload=()=>{row.querySelector('.step-image-data').value=r.result;row.querySelector('.step-preview').innerHTML=`<img src="${esc(r.result)}" class="img-thumbnail" style="max-height:110px">`};r.readAsDataURL(e.target.files[0]);});
    $('memo-grid').addEventListener('click',e=>{const id=e.target.closest('[data-id]')?.dataset.id,m=memos.find(x=>x.id===id);if(!m)return;if(e.target.closest('.view-memo'))preview(m);if(e.target.closest('.edit-memo'))fillForm(m);if(e.target.closest('.delete-memo')&&confirm('Hapus memo ini?')){memos=memos.filter(x=>x.id!==id);persist();render();}});$('reset-data').onclick=()=>{if(confirm('Reset seluruh memo ke data sample?')){memos=[JSON.parse(JSON.stringify(sample))];persist();render();}};render();
});
</script>
@endsection