@extends('layouts.admin')

@section('title', 'Instruksi Kerja Maker')
@section('page-title', 'Instruksi Kerja Maker')

@section('content')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
    .ik-card { transition: transform .15s ease, box-shadow .15s ease; }
    .ik-card:hover { transform:translateY(-2px); box-shadow:0 .5rem 1rem rgba(30,58,95,.12)!important; }
    .ik-paper { width:100%; max-width:210mm; min-height:297mm; box-sizing:border-box; margin:auto; background:#fff; padding:20mm 22mm 25mm; font:10.5pt/1.45 Arial,sans-serif; color:#282828; overflow-wrap:anywhere; }
    .ik-paper .ik-header { display:flex; justify-content:space-between; align-items:flex-end; border-bottom:1pt solid #00529B; padding-bottom:8pt; }
    .ik-paper .ik-logo { height:42pt; max-width:150pt; object-fit:contain; }.ik-paper .ik-company { margin-top:5pt; font-size:10pt; font-weight:700; letter-spacing:.5pt; text-transform:uppercase; }.ik-paper .ik-contact { max-width:230pt; text-align:right; font-size:8.75pt; line-height:1.2; color:#4A5568; }
    .ik-paper .ik-title { margin:18pt 0 4pt; text-align:center; font-size:16pt; font-weight:700; letter-spacing:1.5pt; }.ik-paper .ik-number { margin:0 0 14pt; text-align:center; color:#4A5568; font-size:9pt; }
    .ik-paper .ik-section-title { margin:13pt 0 7pt; padding-bottom:3pt; border-bottom:1pt solid #00529B; color:#00529B; font-size:12pt; font-weight:700; text-transform:uppercase; break-after:avoid; }.ik-paper .ik-text { white-space:pre-line; margin:0; }
    .ik-paper .ik-meta, .ik-paper .ik-check { width:100%; border-collapse:collapse; }.ik-paper .ik-meta { margin-bottom:12pt; background:#F5F7FA; }.ik-paper .ik-meta td { padding:5pt 7pt; vertical-align:top; }.ik-paper .ik-meta td:first-child { width:35%; font-weight:700; }
    .ik-paper .ik-list { margin:0 0 8pt 1.5em; padding:0; }.ik-paper .ik-step, .ik-paper .ik-check-item { margin:10pt 0 13pt; break-inside:avoid; page-break-inside:avoid; }.ik-paper .ik-step-title { margin:0 0 4pt; font-size:11pt; font-weight:700; }.ik-paper .ik-check td { width:50%; padding:5pt; vertical-align:top; border:1pt solid #CBD5E1; }.ik-paper .ik-check img { display:block; width:100%; max-height:125pt; object-fit:contain; margin-top:5pt; }.ik-paper .ik-label { font-size:8.5pt; font-weight:700; color:#00529B; }.ik-paper .ik-signature { margin-top:25pt; text-align:right; break-inside:avoid; page-break-inside:avoid; }.ik-export { width:166mm!important; max-width:166mm!important; padding:0!important; min-height:0!important; }
    #ik-modal .modal-dialog,#ik-settings-modal .modal-dialog { height:calc(100% - 1rem); max-height:calc(100% - 1rem); } #ik-modal .modal-content,#ik-settings-modal .modal-content { height:100%; max-height:100%; } #ik-modal form,#ik-settings-modal form { display:flex; flex:1 1 auto; min-height:0; flex-direction:column; } #ik-modal .modal-body,#ik-settings-modal .modal-body { overflow-y:auto; min-height:0; }
    @media print { @page { size:A4 portrait; margin:20mm 22mm 25mm; } body *{visibility:hidden!important} #ik-preview-modal,#ik-preview-modal .modal-dialog,#ik-preview-modal .modal-content,#ik-preview-modal .modal-body{display:block!important;position:static!important;width:100%!important;max-width:none!important;height:auto!important;padding:0!important;margin:0!important;border:0!important;overflow:visible!important;box-shadow:none!important} #ik-paper,#ik-paper *{visibility:visible!important} #ik-paper{width:100%!important;max-width:none!important;min-height:0;padding:0;margin:0;box-shadow:none!important}.no-print{display:none!important} }
</style>

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h4 class="mb-1 font-headline"><i class="fas fa-list-check text-primary me-2"></i>Instruksi Kerja Maker</h4><p class="text-muted mb-0">Buat acuan dasar yang terstruktur untuk pembuatan checklist dan submission.</p></div>
    <div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="ik-settings"><i class="fas fa-gear me-1"></i>Pengaturan Kop Surat</button><button class="btn btn-primary" id="ik-new"><i class="fas fa-plus me-1"></i>Instruksi Kerja Baru</button></div>
</div>
<div class="card shadow-sm border-0 mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-md-9"><div class="input-group"><span class="input-group-text bg-white"><i class="fas fa-search"></i></span><input id="ik-search" class="form-control" placeholder="Cari nomor atau judul instruksi kerja..."></div></div><div class="col-md-3 text-md-end"><span class="text-muted small" id="ik-count">Total: 0 IK</span></div></div></div></div>
<div id="ik-grid" class="row g-4"></div>

<div class="modal fade" id="ik-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-primary text-white"><h5 class="modal-title" id="ik-modal-title"><i class="fas fa-list-check me-2"></i>Buat Instruksi Kerja Baru</h5><div class="d-flex gap-2"><button type="button" class="btn btn-sm btn-light text-primary" id="ik-toggle-ai"><i class="fas fa-wand-magic-sparkles me-1"></i>AI Generator</button><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div></div><form id="ik-form"><div class="modal-body">
    <div id="ik-ai-panel" class="alert alert-primary d-none"><div class="d-flex justify-content-between mb-2"><strong><i class="fas fa-robot me-1"></i>AI Instruksi Kerja Generator</strong><small>Hasil AI tetap perlu ditinjau</small></div><div class="input-group"><textarea id="ik-ai-topic" class="form-control" rows="2" placeholder="Contoh: Pemeriksaan kabel jaringan di rack server"></textarea><button type="button" class="btn btn-primary" id="ik-generate-ai"><i class="fas fa-sparkles me-1"></i>Generate</button></div><div id="ik-ai-status" class="small mt-2"></div></div>
    <input type="hidden" id="ik-id"><div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label">Nomor IK</label><input id="ik-number" class="form-control" required placeholder="IK/IT-TDI/VIII/2026"></div><div class="col-md-5"><label class="form-label">Judul Instruksi Kerja</label><input id="ik-title" class="form-control" required placeholder="Pemeriksaan kabel jaringan"></div><div class="col-md-3"><label class="form-label">Status</label><select id="ik-status" class="form-select"><option>Draft</option><option>Aktif</option><option>Revisi</option></select></div></div>
    <div class="row g-3"><div class="col-12"><h6 class="border-bottom pb-2 text-primary">1. Tujuan</h6><textarea id="ik-purpose" class="form-control" rows="3" required placeholder="Jelaskan tujuan instruksi kerja..."></textarea></div><div class="col-md-6"><h6 class="border-bottom pb-2 text-primary">2. Alat &amp; Bahan</h6><textarea id="ik-tools" class="form-control" rows="5" required placeholder="Satu alat/bahan per baris..."></textarea></div><div class="col-md-6"><h6 class="border-bottom pb-2 text-primary">3. Kualifikasi Pelaksanaan</h6><textarea id="ik-qualification" class="form-control" rows="5" required placeholder="Kompetensi, kewenangan, atau sertifikasi..."></textarea></div><div class="col-12"><h6 class="border-bottom pb-2 text-primary">4. Uraian Instruksi Kerja</h6><div id="ik-steps"></div><button type="button" class="btn btn-sm btn-outline-primary" id="ik-add-step"><i class="fas fa-plus me-1"></i>Tambah Uraian</button></div><div class="col-12"><h6 class="border-bottom pb-2 text-primary">5. Prosedur Pengecekan</h6><p class="small text-muted">Setiap sub-poin memiliki upload gambar contoh kondisi benar dan salah.</p><div id="ik-checks"></div><button type="button" class="btn btn-sm btn-outline-primary" id="ik-add-check"><i class="fas fa-plus me-1"></i>Tambah Prosedur Pengecekan</button></div></div>
    </div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary"><i class="fas fa-save me-1"></i>Simpan Instruksi Kerja</button></div></form></div></div></div>

<div class="modal fade" id="ik-settings-modal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Pengaturan Kop Surat</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="ik-settings-form"><div class="modal-body"><label class="form-label">Nama Perusahaan</label><input id="ik-company" class="form-control mb-3" required><label class="form-label">Alamat Kantor</label><textarea id="ik-address" class="form-control mb-3" rows="2" required></textarea><label class="form-label">Email</label><input id="ik-email" type="email" class="form-control mb-3" required><label class="form-label">Logo (opsional)</label><input id="ik-logo-file" type="file" accept="image/*" class="form-control"><div id="ik-logo-preview" class="mt-2"></div><hr><h6>AI Generator</h6><select id="ik-provider" class="form-select mb-2"><option value="gemini">Gemini API</option><option value="openai">OpenAI-compatible</option></select><input id="ik-base-url" class="form-control mb-2" placeholder="Base URL provider"><input id="ik-api-key" type="password" class="form-control mb-2" placeholder="API key"><div class="input-group"><select id="ik-model" class="form-select"><option value="">Pilih/load model</option></select><button type="button" class="btn btn-outline-primary" id="ik-load-models">Load Models</button></div><div id="ik-model-status" class="small text-muted mt-2"></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Pengaturan</button></div></form></div></div></div>

<div class="modal fade" id="ik-preview-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-dark text-white no-print"><h5 class="modal-title">Pratinjau Instruksi Kerja</h5><div><button id="ik-print" class="btn btn-sm btn-outline-light me-2">Print</button><button id="ik-pdf" class="btn btn-sm btn-success me-2">Download PDF</button><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div></div><div class="modal-body bg-secondary-subtle p-3 p-md-5"><div id="ik-paper" class="ik-paper shadow"></div></div></div></div></div>

<script>
document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id), modal=id=>bootstrap.Modal.getOrCreateInstance($(id)), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const dataKey='it-instruksi-kerja-maker', settingsKey='tdi_admin_memo_settings_v1';
 const defaults={companyName:'PT. TERA DATA INDONUSA Tbk.',address:'Jl. Inspeksi Pam No.168 17, RT.17/RW.4, Cakung, Jakarta 13910',email:'it.support@terra.co.id',defaultDept:'IT Department',logo:'',provider:'gemini',baseUrl:'https://generativelanguage.googleapis.com/v1beta',apiKey:'',model:''};
 const savedSettings=JSON.parse(localStorage.getItem(settingsKey)||localStorage.getItem('document-maker-settings')||'{}');
 let settings={...defaults,...savedSettings,...@json($adminSettings ?? [])}, docs=@json($documents ?? []), legacyDocs=JSON.parse(localStorage.getItem(dataKey)||'[]');
 if(!settings.apiKey&&settings.geminiApiKey)settings.apiKey=settings.geminiApiKey;
 const date=()=>new Date().toISOString().slice(0,10), providerUrl=()=> $('ik-provider').value==='gemini'?'https://generativelanguage.googleapis.com/v1beta':'https://api.openai.com/v1';
 const csrf=document.querySelector('meta[name="csrf-token"]')?.content||'', documentsUrl='{{ route('admin.instruksi-kerja-maker.documents.store') }}';
 async function persist(doc){const response=await fetch(documentsUrl,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({id:doc.id,document:doc})});if(!response.ok)throw new Error(await responseError(response));return response.json();}
 async function removeDocument(id){const response=await fetch(`${documentsUrl}/${encodeURIComponent(id)}`,{method:'DELETE',headers:{'Accept':'application/json','X-CSRF-TOKEN':csrf}});if(!response.ok)throw new Error(await responseError(response));}
 async function migrateLegacyDocuments(){if(docs.length||!legacyDocs.length)return;for(const doc of legacyDocs){const saved=await persist(doc);docs.push(saved);}localStorage.removeItem(dataKey);}
 function imageReader(file,callback){if(!file)return;const reader=new FileReader();reader.onload=()=>callback(reader.result);reader.readAsDataURL(file);}
 function stepHtml(step={}){return `<div class="ik-step-row border rounded p-3 mb-2"><div class="d-flex justify-content-between"><strong>Sub-poin uraian</strong><button type="button" class="btn btn-sm btn-link text-danger ik-remove">Hapus</button></div><input class="form-control form-control-sm ik-step-title mt-2" value="${esc(step.title)}" placeholder="Judul/tahapan" required><textarea class="form-control form-control-sm ik-step-desc mt-2" rows="2" placeholder="Uraian pelaksanaan" required>${esc(step.description)}</textarea></div>`;}
 function checkHtml(check={}){return `<div class="ik-check-row border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>Sub-poin pengecekan</strong><button type="button" class="btn btn-sm btn-link text-danger ik-remove">Hapus</button></div><input class="form-control form-control-sm ik-check-title mt-2" value="${esc(check.title)}" placeholder="Contoh: Kondisi konektor terpasang sempurna" required><textarea class="form-control form-control-sm ik-check-note mt-2" rows="2" placeholder="Standar/keterangan pengecekan">${esc(check.note)}</textarea><div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label small fw-semibold text-success">Contoh Benar</label><input type="file" accept="image/*" class="form-control form-control-sm ik-correct-file"><input type="hidden" class="ik-correct" value="${esc(check.correct)}"><div class="ik-image-preview correct mt-2">${check.correct?`<img src="${esc(check.correct)}" class="img-thumbnail" style="max-height:110px">`:''}</div></div><div class="col-md-6"><label class="form-label small fw-semibold text-danger">Contoh Salah</label><input type="file" accept="image/*" class="form-control form-control-sm ik-wrong-file"><input type="hidden" class="ik-wrong" value="${esc(check.wrong)}"><div class="ik-image-preview wrong mt-2">${check.wrong?`<img src="${esc(check.wrong)}" class="img-thumbnail" style="max-height:110px">`:''}</div></div></div></div>`;}
 function fill(doc=null){$('ik-form').reset();$('ik-id').value=doc?.id||'';$('ik-number').value=doc?.number||'';$('ik-title').value=doc?.title||'';$('ik-status').value=doc?.status||'Draft';$('ik-purpose').value=doc?.purpose||'';$('ik-tools').value=doc?.tools||'';$('ik-qualification').value=doc?.qualification||'';$('ik-steps').innerHTML='';(doc?.steps?.length?doc.steps:[{}]).forEach(x=>$('ik-steps').insertAdjacentHTML('beforeend',stepHtml(x)));$('ik-checks').innerHTML='';(doc?.checks?.length?doc.checks:[{}]).forEach(x=>$('ik-checks').insertAdjacentHTML('beforeend',checkHtml(x)));$('ik-modal-title').innerHTML=doc?'<i class="fas fa-pen me-2"></i>Edit Instruksi Kerja':'<i class="fas fa-list-check me-2"></i>Buat Instruksi Kerja Baru';modal('ik-modal').show();}
 function read(){return {id:$('ik-id').value||'ik-'+Date.now(),number:$('ik-number').value,title:$('ik-title').value,status:$('ik-status').value,purpose:$('ik-purpose').value,tools:$('ik-tools').value,qualification:$('ik-qualification').value,steps:[...document.querySelectorAll('.ik-step-row')].map(r=>({title:r.querySelector('.ik-step-title').value,description:r.querySelector('.ik-step-desc').value})),checks:[...document.querySelectorAll('.ik-check-row')].map(r=>({title:r.querySelector('.ik-check-title').value,note:r.querySelector('.ik-check-note').value,correct:r.querySelector('.ik-correct').value,wrong:r.querySelector('.ik-wrong').value}))};}
 function render(){const q=$('ik-search').value.toLowerCase();const list=docs.filter(d=>`${d.number} ${d.title}`.toLowerCase().includes(q));$('ik-count').textContent=`Total: ${list.length} IK`;$('ik-grid').innerHTML=list.map(d=>`<div class="col-md-6 col-xl-4"><div class="card ik-card h-100 shadow-sm border-0"><div class="card-body"><div class="d-flex justify-content-between mb-2"><span class="badge text-bg-primary">${esc(d.status)}</span><small class="text-muted">${esc(d.number)}</small></div><h5>${esc(d.title)}</h5><p class="small text-muted mb-3">${esc(d.purpose).slice(0,120)}${d.purpose.length>120?'...':''}</p><small class="text-muted">${d.steps?.length||0} uraian · ${d.checks?.length||0} prosedur pengecekan</small></div><div class="card-footer bg-white border-0 d-flex gap-2"><button class="btn btn-sm btn-outline-primary ik-view" data-id="${d.id}">Preview</button><button class="btn btn-sm btn-outline-secondary ik-edit" data-id="${d.id}">Edit</button><button class="btn btn-sm btn-outline-danger ik-delete" data-id="${d.id}">Hapus</button></div></div></div>`).join('')||'<div class="col-12"><div class="alert alert-light text-center">Belum ada Instruksi Kerja.</div></div>';}
 function preview(d){const logo=settings.logo?`<img src="${esc(settings.logo)}" class="ik-logo">`:'<strong class="ik-logo" style="display:inline-block;font-size:18pt;color:#00529B">TDI</strong>';const list=(d.tools||'').split('\n').filter(Boolean).map(x=>`<li>${esc(x)}</li>`).join('');const steps=(d.steps||[]).map((x,i)=>`<div class="ik-step"><h4 class="ik-step-title">${i+1}. ${esc(x.title)}</h4><p class="ik-text">${esc(x.description)}</p></div>`).join('');const checks=(d.checks||[]).map((x,i)=>`<div class="ik-check-item"><h4 class="ik-step-title">${i+1}. ${esc(x.title)}</h4><p class="ik-text">${esc(x.note)}</p><table class="ik-check"><tr><td><span class="ik-label">CONTOH BENAR</span>${x.correct?`<img src="${esc(x.correct)}">`:'<p class="text-muted">Gambar belum diunggah.</p>'}</td><td><span class="ik-label">CONTOH SALAH</span>${x.wrong?`<img src="${esc(x.wrong)}">`:'<p class="text-muted">Gambar belum diunggah.</p>'}</td></tr></table></div>`).join('');$('ik-paper').innerHTML=`<header class="ik-header"><div>${logo}<div class="ik-company">${esc(settings.companyName)}</div></div><div class="ik-contact">${esc(settings.address)}<br>Email: ${esc(settings.email)}</div></header><h2 class="ik-title">INSTRUKSI KERJA</h2><p class="ik-number">Nomor: ${esc(d.number)} · Status: ${esc(d.status)}</p><table class="ik-meta"><tr><td>Judul Instruksi Kerja</td><td>${esc(d.title)}</td></tr></table><h3 class="ik-section-title">1. Tujuan</h3><p class="ik-text">${esc(d.purpose)}</p><h3 class="ik-section-title">2. Alat &amp; Bahan</h3><ul class="ik-list">${list||'<li>-</li>'}</ul><h3 class="ik-section-title">3. Kualifikasi Pelaksanaan</h3><p class="ik-text">${esc(d.qualification)}</p><h3 class="ik-section-title">4. Uraian Instruksi Kerja</h3>${steps||'<p>-</p>'}<h3 class="ik-section-title">5. Prosedur Pengecekan</h3>${checks||'<p>-</p>'}<div class="ik-signature"><p>Disusun untuk menjadi acuan pelaksanaan,</p><p style="margin-bottom:55pt">IT Support</p><strong>${esc(settings.companyName)}</strong></div>`;modal('ik-preview-modal').show();}
 async function generate(){const topic=$('ik-ai-topic').value.trim();if(!topic)return $('ik-ai-status').textContent='Masukkan topik terlebih dahulu.';if(!settings.apiKey||!settings.model)return $('ik-ai-status').textContent='Isi API key dan model melalui Pengaturan Kop Surat.';const button=$('ik-generate-ai');button.disabled=true;$('ik-ai-status').textContent='AI sedang menyusun draft...';const prompt=`Buat Instruksi Kerja berbahasa Indonesia untuk topik: ${topic}. Kembalikan JSON valid saja dengan keys title,purpose,tools (string per baris),qualification,steps (array objects title,description),checks (array objects title,note,correct,wrong). correct dan wrong harus string kosong karena gambar diunggah manual. Buat minimal 4 steps dan 3 checks.`;try{let response;if(settings.provider==='gemini'){response=await fetch(`${settings.baseUrl.replace(/\/$/,'')}/models/${settings.model}:generateContent?key=${encodeURIComponent(settings.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});}else{response=await fetch(`${settings.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${settings.apiKey}`},body:JSON.stringify({model:settings.model,messages:[{role:'user',content:prompt}],temperature:.3})});}if(!response.ok)throw new Error(`Provider AI mengembalikan status ${response.status}.`);const body=await response.json();const text=settings.provider==='gemini'?body.candidates?.[0]?.content?.parts?.[0]?.text:body.choices?.[0]?.message?.content;if(!text)throw new Error('Respons AI kosong.');const generated=JSON.parse(text.replace(/^```json\s*|```$/g,'').trim());$('ik-title').value=generated.title||'';$('ik-purpose').value=generated.purpose||'';$('ik-tools').value=generated.tools||'';$('ik-qualification').value=generated.qualification||'';$('ik-steps').innerHTML=(generated.steps||[]).map(stepHtml).join('');$('ik-checks').innerHTML=(generated.checks||[]).map(checkHtml).join('');$('ik-ai-status').textContent='Draft berhasil dibuat. Silakan tinjau dan lengkapi gambar.';}catch(e){$('ik-ai-status').textContent=`Gagal membuat draft: ${e.message}`;}finally{button.disabled=false;}}
 function loadSettings(){['company','address','email','provider','base-url','api-key','model'].forEach(k=>{const map={'company':'companyName','address':'address','email':'email','provider':'provider','base-url':'baseUrl','api-key':'apiKey','model':'model'};$('ik-'+k).value=settings[map[k]]||''});$('ik-logo-preview').innerHTML=settings.logo?`<img src="${esc(settings.logo)}" style="max-height:70px;max-width:160px">`:'';}
 $('ik-new').onclick=()=>fill();$('ik-search').oninput=render;$('ik-toggle-ai').onclick=()=>{$('ik-ai-panel').classList.toggle('d-none');};$('ik-generate-ai').onclick=generate;$('ik-add-step').onclick=()=>$('ik-steps').insertAdjacentHTML('beforeend',stepHtml());$('ik-add-check').onclick=()=>$('ik-checks').insertAdjacentHTML('beforeend',checkHtml());
 $('ik-form').onsubmit=async e=>{e.preventDefault();const d=read(),i=docs.findIndex(x=>x.id===d.id);try{const saved=await persist(d);i<0?docs.unshift(saved):docs[i]=saved;render();modal('ik-modal').hide();}catch(error){alert(`Gagal menyimpan Instruksi Kerja: ${error.message}`);}};$('ik-settings').onclick=()=>{loadSettings();modal('ik-settings-modal').show();};$('ik-settings-form').onsubmit=async e=>{e.preventDefault();settings={...settings,companyName:$('ik-company').value,address:$('ik-address').value,email:$('ik-email').value,provider:$('ik-provider').value,baseUrl:$('ik-base-url').value.replace(/\/$/,'')||providerUrl(),apiKey:$('ik-api-key').value.trim(),model:$('ik-model').value,geminiApiKey:$('ik-provider').value==='gemini'?$('ik-api-key').value.trim():settings.geminiApiKey||''};try{settings=await saveAdminSettings(settings);modal('ik-settings-modal').hide();}catch(error){alert(`Gagal menyimpan pengaturan: ${error.message}`);}};
 $('ik-logo-file').onchange=e=>imageReader(e.target.files[0],src=>{settings.logo=src;$('ik-logo-preview').innerHTML=`<img src="${esc(src)}" style="max-height:70px;max-width:160px">`;});$('ik-steps').onclick=e=>{if(e.target.closest('.ik-remove'))e.target.closest('.ik-step-row').remove();};$('ik-checks').onclick=e=>{if(e.target.closest('.ik-remove'))e.target.closest('.ik-check-row').remove();};$('ik-checks').onchange=e=>{if(!e.target.matches('input[type=file]'))return;const row=e.target.closest('.ik-check-row'),correct=e.target.classList.contains('ik-correct-file');imageReader(e.target.files[0],src=>{row.querySelector(correct?'.ik-correct':'.ik-wrong').value=src;row.querySelector(correct?'.correct':'.wrong').innerHTML=`<img src="${esc(src)}" class="img-thumbnail" style="max-height:110px">`;});};$('ik-grid').onclick=async e=>{const id=e.target.dataset.id,d=docs.find(x=>x.id===id);if(!d)return;if(e.target.classList.contains('ik-view'))preview(d);if(e.target.classList.contains('ik-edit'))fill(d);if(e.target.classList.contains('ik-delete')&&confirm('Hapus Instruksi Kerja ini?')){try{await removeDocument(id);docs=docs.filter(x=>x.id!==id);render();}catch(error){alert(`Gagal menghapus Instruksi Kerja: ${error.message}`);}}};
 function openAiModels(data){const source=Array.isArray(data)?data:data?.data||data?.models||data?.result?.data||data?.result?.models||data?.result||[];return Array.isArray(source)?source:[];}
 async function responseError(response){const text=await response.text();try{const payload=JSON.parse(text);return payload?.error?.message||payload?.message||payload?.detail||text;}catch{return text;}}
 $('ik-print').onclick=()=>window.print();$('ik-pdf').onclick=()=>{if(typeof html2pdf==='undefined')return alert('Library PDF belum termuat.');const paper=$('ik-paper');paper.classList.add('ik-export');html2pdf().set({margin:[20,22,25,22],filename:`Instruksi_Kerja_${$('ik-number').value||'Official'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},pagebreak:{mode:['css','legacy'],avoid:['.ik-meta','.ik-step','.ik-check-item','.ik-signature']},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(paper).save().catch(err=>alert(`Gagal membuat PDF: ${err.message}`)).finally(()=>paper.classList.remove('ik-export'));};
  $('ik-load-models').onclick=async()=>{const key=$('ik-api-key').value.trim(),provider=$('ik-provider').value,base=($('ik-base-url').value||providerUrl()).trim().replace(/\/$/,''),status=$('ik-model-status'),select=$('ik-model'),selected=select.value;if(!key)return status.textContent='Masukkan API key terlebih dahulu.';status.textContent='Memuat model...';try{const r=provider==='gemini'?await fetch(`${base}/models?key=${encodeURIComponent(key)}`):await fetch(`${base}/models`,{headers:{Accept:'application/json',Authorization:`Bearer ${key}`}});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw new Error(`Respons model bukan JSON (${r.status}): ${text.slice(0,180)}`);}if(!r.ok)throw new Error(`Gagal memuat model (${r.status}): ${(data?.error?.message||data?.message||data?.detail||text).slice(0,180)}`);const source=provider==='gemini'?(data.models||[]):(Array.isArray(data)?data:data.data||data.models||data.result?.data||data.result?.models||data.result||[]),models=(Array.isArray(source)?source:[]).filter(x=>provider!=='gemini'||(x.supportedGenerationMethods||[]).includes('generateContent'));if(!models.length)throw new Error('Provider tidak mengembalikan model yang dapat digunakan.');select.innerHTML=models.map(x=>{const n=(typeof x==='string'?x:x.name||x.id||x.model||'').replace(/^models\//,'');return n?`<option value="${esc(n)}">${esc(n)}</option>`:'';}).join('');select.value=[...select.options].some(x=>x.value===selected)?selected:select.options[0].value;status.textContent=`${models.length} model tersedia.`;}catch(e){status.textContent=`${e.message}${e instanceof TypeError?' Periksa Base URL dan CORS endpoint.':''}`;}};$('ik-provider').onchange=()=>{$('ik-base-url').value=providerUrl();$('ik-model').innerHTML='<option value="">Pilih/load model</option>';};migrateLegacyDocuments().then(render).catch(error=>{console.error(error);render();});
});
</script>
@endsection